apiVersion: v1
kind: Pod

metadata:
  name: web
  labels:
    name: web
    app: demo

spec:
  containers:
  - name: web
    image: "acinwinstack/redis_count:pod"
    env:
    - name: "REDIS_HOST"
      value: "172.17.0.7"
    - name: "NAME"
      value: "Alfie Chen"
    ports:
    - containerPort: 80
